### PR TITLE
String2.escapeMarkupId() has to escape with two backslashes instead of one

### PR DESCRIPTION
**Pull request by johnjcool**
selectors.html - "If you wish to use any of the meta-characters ( such as !"#$%&'()*+,./:;<=>?@[\]^`{|}~ ) as a literal part of a name, you must escape the character with two backslashes: \\."

### CODE REVIEW

**Comment by martin-g** [comment]
Due to the code reformating it is hard to see what exactly has been changed.
Please revert any change that is not related to the fix!
Thanks!

**Comment by johnjcool** [comment]
reverted

**Comment by martin-g** [comment]
Failed tests:   $componentWithDotsInTheMarkupId(de.agilecoders.wicket.jquery.JQueryTest): (..)

**Comment by martin-g** [comment]
Fixed the test!
Thanks!

**Comment by johnjcool** [comment]
Many thanks. 
Could you please make a release?

**Comment by martin-g** [comment]
Done!
0.1.7/0.2.4/2.0.0-M2 are released!

**Pull request merged**
