### PR TITLE
Dependencies 10.x

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by solomax** [comment]
@martin-g I believe this one (as well as `wicket-bootstrap:6.0.X` `wicket-bootstrap:7.0.X` should be released ....

Jackson version is not aligned with wicketstuff :(

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
I have troubles releasing this:
```
[INFO] [ERROR] We have duplicated artifacts attached.
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time:  4.805 s
[INFO] [INFO] Finished at: 2023-08-25T10:52:32+03:00
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.3.0:jar-no-fork (attach-sources) on project jquery-selectors: Presumably you have configured maven-source-plugn to execute twice times in your build. You have to configure a classifier for at least on of them. -> [Help 1]
[INFO] [ERROR] 
```

I moved all `build>plugins` to `build>pluginManagement` and removed the parent pom (oss-parent) but still the release fails...

**Comment by solomax** [comment]
> I have troubles releasing this:

let me check

**Comment by solomax** [comment]
According to https://stackoverflow.com/questions/76305897/maven-build-fails-after-upgrading-to-maven-source-plugin-from-3-2-1-to-3-3-0 change need to be done is:

`<goal>jar</goal> -> <goal>jar-no-fork</goal>`

@martin-g  Can you please try it?

**Comment by martin-g** [comment]
Thanks! It worked!

**Comment by martin-g** [comment]
Now the javadoc plugin fails ...
I have work to do :-)

**Comment by solomax** [comment]
> Now the javadoc plugin fails

Unfortunately I can't see these errors :(

Maybe in case of javadoc `jar-no-fork` should be used? :)

**Comment by martin-g** [comment]
Finally all is good!
4.0.1 has been released.

**Comment by martin-g** [comment]
It seems it does not use the expected versions:
```
    [INFO] <<< source:2.1.2:test-jar (default) < generate-sources @ jquery-selectors <<<
```
but I really don't have any more time to spend on this right now.

**Comment by solomax** [comment]
> It seems it does not use the expected versions:

I guess this is because you have moved everything to `pluginManagement` :)

> but I really don't have any more time to spend on this right now.

no problem :)

**Pull request merged**
